# This is a basic workflow to help you get started with Actions
name: TestCase_Execution
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
       BROWSER: Chrome
       MY_LICENSE: ${{secrets.PROVAR_LICENSE}}
       PROVAR_HOME: ${{github.workspace}}/ProvarHome
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Run build
      run: |
        sudo apt-get update && sudo apt-get upgrade
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >>sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y install google-chrome-stable
        mkdir $GITHUB_WORKSPACE/ProvarHome
        curl -O https://download.provartesting.com/latest/Provar_ANT_latest.zip
        unzip -o Provar_ANT_latest.zip -d ProvarHome
        rm Provar_ANT_latest.zip
        mkdir -p $PROVAR_HOME/Provar/.licenses
        echo "$MY_LICENSE" >> $PROVAR_HOME/Provar/.licenses/License.properties
        cd $GITHUB_WORKSPACE/Demo/ANT
        xvfb-run ant -f build_jenkins.xml
    - uses: actions/upload-artifact@v2
      with:
        name: Execution Report
        path: ${{github.workspace}}/Demo/ANT/Results
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Execution Report1
        path: ${{github.workspace}}/Demo/ANT/Results
