name: TestCase_Execution
on:
  workflow_dispatch:
  
jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      BROWSER: Chrome
      MY_LICENSE: ${{ secrets.PROVAR_LICENSE }}
      PROVAR_HOME: ${{ github.workspace }}/ProvarHome

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Chrome and Provar
      - name: Run build
        run: |
          sudo apt-get update && sudo apt-get upgrade
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >>sudo tee -a /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get -y install google-chrome-stable
          mkdir $GITHUB_WORKSPACE/ProvarHome
          curl -O https://download.provartesting.com/latest/Provar_ANT_latest.zip
          unzip -o Provar_ANT_latest.zip -d ProvarHome
          rm Provar_ANT_latest.zip
          mkdir -p $PROVAR_HOME/Provar/.licenses
          echo "$MY_LICENSE" >> $PROVAR_HOME/Provar/.licenses/License.properties
          sh generate_buildxml.sh >> $GITHUB_WORKSPACE/ANT
          cd $GITHUB_WORKSPACE/ANT
          xvfb-run ant -f build.xml

      # Upload the execution report on success
      - uses: actions/upload-artifact@v4
        with:
          name: Execution Report
          path: ${{ github.workspace }}/Demo/ANT/Results

      # Upload execution report on failure
      - uses: actions/upload-artifact@v4
        if: failure()  # This step will only run if the previous steps fail
        with:
          name: Execution Report1
          path: ${{ github.workspace }}/Demo/ANT/Results
