name: TestCase_Execution
on:
  workflow_dispatch:
  
jobs:
  build_test:
    runs-on: ubuntu-latest
    env:
      BROWSER: Chrome
      MY_LICENSE: ${{ secrets.PROVAR_LICENSE }}
      PROVAR_HOME: ${{ github.workspace }}/ProvarHome

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Install Chrome and Provar
      - name: Run build
        run: |
          
          
          mkdir $GITHUB_WORKSPACE/ProvarHome
          curl -O https://download.provartesting.com/latest/Provar_ANT_latest.zip
          unzip -o Provar_ANT_latest.zip -d ProvarHome
          rm Provar_ANT_latest.zip
          mkdir -p $PROVAR_HOME/Provar/.licenses
          echo "$MY_LICENSE" >> $PROVAR_HOME/Provar/.licenses/License.properties
          sh generate_buildxml.sh >> $GITHUB_WORKSPACE/ANT/build.xml
          cd $GITHUB_WORKSPACE/ANT
          xvfb-run ant -f build.xml

